add_newline = true 
# prompt customization
format = """$all$directory$character"""
# move the rest of the prompt to the right
right_format = """$all"""

[cmd_duration]
#min_time = 5000
#format = "took [⏱ ]"

[directory]
truncation_length = 8
truncation_symbol = '.../'
truncate_to_repo = true

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = 'on [$hostname](bold yellow) '
trim_at = "."
disabled = false

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"
#vicmd_symbol = "[](bold green)"

[git_branch]
symbol = ' '
#truncation_length = 4
#truncation_symbol = ''
#ignore_branches = ['master', 'main']

[git_status]
ahead = " "
behind = " "
diverged = " "
renamed = "➜ "
deleted = " "
staged = " "
untracked = " "


